name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildozer
        uses: GeorgiYanev/buildozer-action@v1
        with:
          command: buildozer android debug
          
